[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "D"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]

[tool.ruff.pydocstyle]
convention = "pep257"

[tool.mypy]
strict = true
disallow_untyped_calls = false
allow_redefinition = true

[tool.pyright]
reportRedeclaration = false

[tool.poetry]
name = "base"
version = "0.1.0"
description = ""
authors = ["AndBoyS <andboyxd@gmail.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "~3.11"

[tool.poetry.group.dev.dependencies]
mypy = "^1.9.0"
ruff = "^0.3.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
