[tool.ruff]
line-length = 120

[tool.mypy]
strict = true
disallow_untyped_calls = false
allow_redefinition = true

[tool.poetry]
name = "base-template"
version = "0.1.0"
description = ""
authors = ["AndBoyS <andboyxd@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.11"
mypy = "^1.9.0"
ruff = "^0.3.7"
pre-commit = "^3.7.0"
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
